#add this file to your meteor package as `.travis.yml`
language: node_js
node_js:
  - "0.10"
before_install:
  - "npm install -g jsonplaceholder"
  - "PORT=3002 jsonplaceholder &"
  - "curl -L http://git.io/ejPSng | /bin/sh"